name: "Chromatic"

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    env: 
      CHROMATIC_ARCHIVE_LOCATION: "./test-results/chromatic-archives"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        # ⚠️ Pick one of these, matching the package manager for your project
        run: npm ci
        # run: pnpm install
        # run: yarn install --immutable --immutable-cache --check-cache

      # ...
      # Your existing setup to run Playwright tests
      # ...
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          # ⚠️ enable playwright
          playwright: true
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        # ⚠️ Optionally configure the archive loation with env vars
